# Generated by Django 4.2.20 on 2026-06-28 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfere_at', models.DateField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('compte_destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferts_recus', to=settings.AUTH_USER_MODEL)),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferts_emis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-transfere_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.CharField(max_length=100)),
                ('table_id', models.CharField(help_text='Référence unique au format : nom_table_id_123', max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=3, help_text='Crédit (+) ou débit (-) en caisse', max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction caisse',
                'verbose_name_plural': 'Transactions caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSoldeCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_at', models.DateField()),
                ('calcul_solde', models.DecimalField(decimal_places=3, default=0, help_text='Solde calculé automatiquement', max_digits=11)),
                ('correction_solde', models.DecimalField(decimal_places=3, default=0, help_text='Correction manuelle appliquée', max_digits=11)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Administrateur ayant effectué la correction', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='soldes_administres', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Commercial concerné par ce solde', on_delete=django.db.models.deletion.RESTRICT, related_name='historiques_solde', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique solde compte',
                'verbose_name_plural': 'Historiques soldes compte',
                'ordering': ['-solde_at'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('naissance_at', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('embauche_at', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('type_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/')),
                ('salaire', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
