# Generated by Django 4.2.20 on 2026-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfere',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
