# Generated by Django 4.2.20 on 2026-07-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_libelletransaction_transaction_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hist_solde_compte',
            field=models.ForeignKey(blank=True, help_text='Renseigné une fois la transaction intégrée à un solde : sert de statut « Soldé »', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='administration.historiquesoldecompte'),
        ),
    ]
