# Generated by Django 4.2.20 on 2026-07-02 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_transaction_hist_solde_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='transfere',
            constraint=models.CheckConstraint(check=models.Q(('montant__gt', 0)), name='transfere_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='transfere',
            constraint=models.CheckConstraint(check=models.Q(('compte_source', models.F('compte_destination')), _negated=True), name='transfere_comptes_differents'),
        ),
    ]
