# Generated by Django 4.2.20 on 2026-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourNonOuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('type_jour', models.CharField(choices=[('Férié national', 'Férié national'), ('Fermeture entreprise', 'Fermeture entreprise'), ('Congé exceptionnel', 'Congé exceptionnel')], default='Férié national', max_length=30)),
                ('concerne_livraison', models.BooleanField(default=True, help_text="Décoché si ce jour férié n'empêche pas réellement les livraisons")),
            ],
            options={
                'verbose_name': 'Jour non ouvré',
                'verbose_name_plural': 'Jours non ouvrés',
                'ordering': ['date'],
            },
        ),
    ]
