# Generated by Django 4.2.20 on 2026-08-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerrouillageConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=150, unique=True)),
                ('echecs', models.PositiveSmallIntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verrouillage de connexion',
                'verbose_name_plural': 'Verrouillages de connexion',
            },
        ),
        migrations.CreateModel(
            name='CodeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_connexion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de connexion',
                'verbose_name_plural': 'Codes de connexion',
                'ordering': ['-cree_le'],
            },
        ),
    ]
