# Generated by Django 4.2.20 on 2026-06-28 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStockInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historiques_stock_initial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique stock initial',
                'verbose_name_plural': 'Historiques stock initial',
                'ordering': ['-stock_initial_at'],
            },
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite', models.CharField(blank=True, choices=[('Pièce', 'Pièce'), ('Kg', 'Kg'), ('Litre', 'Litre')], default='Kg', max_length=10, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimum', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Matière première',
                'verbose_name_plural': 'Matières premières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MatierePremiereFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=50)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Famille de matière première',
                'verbose_name_plural': 'Familles de matières premières',
                'ordering': ['famille'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0, help_text='Stock actuel en unités')),
                ('quantite_minimale', models.IntegerField(default=0, help_text='Quantité minimale à maintenir')),
                ('taille', models.CharField(blank=True, choices=[('Mini', 'Mini'), ('Moyenne', 'Moyenne'), ('Grande', 'Grande')], default='Moyenne', max_length=10, null=True)),
                ('poids', models.PositiveIntegerField(blank=True, help_text='Poids en grammes', null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('is_produit_semi_fini', models.BooleanField(default=False)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, help_text='Quantité produite par cette recette', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('observation', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recettes', to='production.produit')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
            },
        ),
        migrations.CreateModel(
            name='RecetteDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recette_details', to='production.matierepremiere')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='production.recette')),
            ],
            options={
                'verbose_name': 'Détail de recette',
                'verbose_name_plural': 'Détails de recettes',
            },
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='matiere_premiere_famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matieres_premieres', to='production.matierepremierefamille'),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='produit',
            field=models.ForeignKey(blank=True, help_text='Renseigner uniquement si cette matière est un produit semi-fini', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='matieres_premieres_semi_fini', to='production.produit'),
        ),
        migrations.CreateModel(
            name='HistoriqueStockInitialDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcul_stock', models.PositiveSmallIntegerField(blank=True, help_text='Stock calculé système', null=True)),
                ('reel_stock', models.PositiveSmallIntegerField(blank=True, help_text='Stock réel constaté', null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('historique_stock_initial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='production.historiquestockinitial')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historiques_stock', to='production.produit')),
            ],
            options={
                'verbose_name': 'Détail historique stock initial',
                'verbose_name_plural': 'Détails historique stock initial',
            },
        ),
        migrations.CreateModel(
            name='CommandeInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison_at', models.DateField(blank=True, null=True)),
                ('quantite_commander', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('quantite_produite', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_stock_maj', models.BooleanField(default=False, help_text='Indique si le stock a été mis à jour')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commandes_internes', to='production.produit')),
            ],
            options={
                'verbose_name': 'Commande interne',
                'verbose_name_plural': 'Commandes internes',
                'ordering': ['-livraison_at'],
            },
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie_at', models.DateField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('hist_stock_initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_sortie', to='production.historiquestockinitial')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_sortie', to='production.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_sortie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de sortie',
                'verbose_name_plural': 'Bons de sortie',
                'ordering': ['-sortie_at'],
            },
        ),
        migrations.CreateModel(
            name='BonRestitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restitution_at', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('hist_stock_initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_restitution', to='production.historiquestockinitial')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_restitution', to='production.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_restitution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de restitution',
                'verbose_name_plural': 'Bons de restitution',
                'ordering': ['-restitution_at'],
            },
        ),
    ]
