# Generated by Django 4.2.20 on 2026-07-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_historiquestockinitial_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquestockinitialdetaille',
            name='historique_stock_initial',
        ),
        migrations.RemoveField(
            model_name='historiquestockinitialdetaille',
            name='produit',
        ),
        migrations.AlterField(
            model_name='bonrestitution',
            name='hist_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_restitution', to='commercial.historiquestockinitial'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='hist_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_sortie', to='commercial.historiquestockinitial'),
        ),
        migrations.DeleteModel(
            name='HistoriqueStockInitial',
        ),
        migrations.DeleteModel(
            name='HistoriqueStockInitialDetaille',
        ),
    ]
