# Generated by Django 4.2.20 on 2026-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_historiquestockinitialdetaille_historique_stock_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremierefamille',
            name='famille',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
