# Generated by Django 4.2.20 on 2026-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_matierepremierefamille_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='unite',
            field=models.CharField(blank=True, choices=[('Pièce', 'Pièce'), ('Kg', 'Kg'), ('Litre', 'Litre')], default='Pièce', max_length=10, null=True),
        ),
    ]
