# Generated by Django 4.2.20 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_recette_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeinterne',
            name='unite',
            field=models.CharField(blank=True, choices=[('Pièce', 'Pièce'), ('Kg', 'Kg'), ('Litre', 'Litre')], default='Pièce', max_length=10, null=True),
        ),
    ]
