# Generated by Django 4.2.20 on 2026-07-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_commandeinterne_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeinterne',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commandeinterne',
            name='unite',
        ),
        migrations.AddField(
            model_name='commandeinterne',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='commandes_internes', to='production.recette'),
        ),
    ]
