# Generated by Django 4.2.20 on 2026-07-28 08:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_fournisseur_raison_sociale'),
        ('production', '0006_remove_commandeinterne_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonrestitution',
            name='hist_stock_initial',
        ),
        migrations.RemoveField(
            model_name='bonrestitution',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='bonrestitution',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='hist_stock_initial',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='quantite',
        ),
        migrations.AddField(
            model_name='bonrestitution',
            name='historique_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_restitution', to='commercial.historiquestockinitial'),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='historique_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_sortie', to='commercial.historiquestockinitial'),
        ),
        migrations.CreateModel(
            name='BonSortieDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='production.bonsortie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bon_sortie_details', to='production.produit')),
            ],
            options={
                'verbose_name': 'Détail de bon de sortie',
                'verbose_name_plural': 'Détails de bons de sortie',
            },
        ),
        migrations.CreateModel(
            name='BonRestitutionDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('bon_restitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='production.bonrestitution')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bon_restitution_details', to='production.produit')),
            ],
            options={
                'verbose_name': 'Détail de bon de restitution',
                'verbose_name_plural': 'Détails de bons de restitution',
            },
        ),
    ]
