# Generated by Django 4.2.20 on 2026-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_sauvegarde', models.CharField(choices=[('Complète', 'Complète'), ('Structure seule', 'Structure seule'), ('Données seules', 'Données seules')], default='Complète', max_length=20)),
                ('chiffre', models.BooleanField(default=True, verbose_name='Chiffré')),
                ('taille', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('reussie', models.BooleanField(default=False, verbose_name='Réussie')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('chemin_fichier', models.CharField(blank=True, max_length=500, null=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('cree_par', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-created_at'],
            },
        ),
    ]
