
"""
setting.py

Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config # ajouté par Claude
import os  # Ajouté pour les chemins de fichiers statiques et médias

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-1wocmxu_h4g*6nwc%vg==e)605$)7blu4_p_xqzi=4%nslf4(%'
# ajouté par Claude
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1wocmxu_h4g*6nwc%vg==e)605$)7blu4_p_xqzi=4%nslf4(%')

# Sel utilisé pour encoder les ID dans les URLs (voir core/converters.py).
# Distinct de SECRET_KEY pour pouvoir le faire tourner indépendamment
# (rotation = les anciens liens partagés deviennent invalides).
HASHIDS_SALT = config('HASHIDS_SALT', default=SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# ajouté par Claude
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS = []
# ajouté par Claude
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Applications tierces
    'django_extensions',      # ✅ Pour les commandes graph_models, etc.
    'crispy_forms',           # Pour django-crispy-forms
    'crispy_bootstrap5',      # Pour le thème Bootstrap 5
    
    # Vos applications Django
    'core',
    'administration',
    'commercial',
    'production',
    'backups',
]

# Configuration de Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # ajouté par Claude
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RequestLogContextMiddleware',  # après Authentication : request.user est résolu
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF = 'config.urls'
ROOT_URLCONF = 'patisserie_management.urls' # ajouté par Claude

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ✅ Ajout du dossier templates global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.is_administration',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'
WSGI_APPLICATION = 'patisserie_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gestion_patisseries',           # ✅ Votre base de données
        'USER': 'admin',                          # ✅ L'utilisateur que vous venez de créer
        'PASSWORD': 'Mrhssoc#patisseries',       # ✅ Le mot de passe que vous avez défini
        'HOST': 'localhost',                     # ✅ MySQL sur le même serveur
        'PORT': '3306',                          # ✅ Port par défaut
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    },
    # Base SÉPARÉE (SQLite) pour les métadonnées de l'app "backups" — jamais
    # dans 'default' : une restauration de 'default' remplace TOUT son
    # contenu (y compris sa propre table de suivi des sauvegardes) par
    # l'instantané du dump restauré, ce qui efface ou fige l'historique des
    # sauvegardes créées après ce dump. Isoler cette table dans sa propre
    # base, jamais touchée par mysqldump/mysql, la rend insensible aux
    # restaurations de 'default'. Voir backups/db_router.py.
    'sauvegardes': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_backups' / 'metadonnees.sqlite3',
    },
}

DATABASE_ROUTERS = ['backups.db_router.SauvegardesRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'  # ✅ Changé en français

TIME_ZONE = 'Africa/Tunis'  # ✅ Changé pour le fuseau horaire tunisien

USE_I18N = True

USE_TZ = False  # Données stockées en heure locale Tunisia, pas en UTC


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # ✅ Dossier static global
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ✅ Dossier pour collectstatic

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # ✅ Dossier pour les fichiers uploadés

# Sauvegardes de la base de données (app "backups") — volontairement HORS de
# MEDIA_ROOT : ces fichiers contiennent un dump complet des données et ne
# doivent jamais être exposés via une URL statique/media, uniquement via
# SauvegardeDownloadView (contrôle d'accès + déchiffrement à la volée).
DB_BACKUPS_DIR = BASE_DIR / 'db_backups'
DB_BACKUPS_DIR.mkdir(parents=True, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth routing
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ✅ Ajout d'une configuration pour les messages (optionnel)
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# ─────────────────────────────────────────────────────────────────────────────
# Logging — deux journaux séparés et étanches :
#   logs/technical/ : erreurs Python/Django/HTTP/SQL/API — pour les développeurs
#   logs/audit/     : opérations métier critiques (CRUD, auth, import/export,
#                     sauvegarde) — pour les administrateurs
# Le détail des choix (rotation, filtre, masquage) est documenté dans le chat/
# la doc du projet ; voir aussi core/logging_filters.py et core/audit.py.
# ─────────────────────────────────────────────────────────────────────────────

LOGS_DIR = BASE_DIR / 'logs'
(LOGS_DIR / 'technical').mkdir(parents=True, exist_ok=True)
(LOGS_DIR / 'audit').mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'filters': {
        'audit_context': {
            '()': 'core.logging_filters.AuditContextFilter',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    'formatters': {
        'technical': {
            'format': '{asctime} {levelname} {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
        },
        'audit': {
            'format': (
                '{asctime} | {action} | user={user} (id={user_id}, rôle={role}) | ip={ip} '
                '| {device_type}/{os}/{browser} | {method} {path} | {module}.{funcName}:{lineno} '
                '| table={table} id={record_id} | avant={old_value} | après={new_value} | {message}'
            ),
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'WARNING',
            'formatter': 'technical',
        },
        # Erreurs techniques : rotation quotidienne, 30 jours conservés.
        'technical_file': {
            'class': 'core.logging_handlers.SafeTimedRotatingFileHandler',
            'filename': LOGS_DIR / 'technical' / 'technical.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'encoding': 'utf-8',
            'level': 'WARNING',
            'formatter': 'technical',
        },
        # E-mail aux admins sur les 500 en production (jamais en DEBUG).
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'filters': ['require_debug_false'],
        },
        # Audit métier : même politique de rétention, fichier et filtre distincts.
        'audit_file': {
            'class': 'core.logging_handlers.SafeTimedRotatingFileHandler',
            'filename': LOGS_DIR / 'audit' / 'audit.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'encoding': 'utf-8',
            'level': 'INFO',
            'formatter': 'audit',
            'filters': ['audit_context'],
        },
    },

    'loggers': {
        # Erreurs serveur (500) et exceptions non gérées remontées par Django.
        'django.request': {
            'handlers': ['technical_file', 'mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Failles/anomalies de sécurité détectées par Django (CSRF, hôte
        # invalide, en-têtes suspects...).
        'django.security': {
            'handlers': ['technical_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Erreurs SQL importantes seulement (le logger par défaut de Django
        # loggue TOUTES les requêtes en DEBUG : on ne l'active pas, on ne
        # garde que les erreurs réelles remontées par le driver/l'ORM).
        'django.db.backends': {
            'handlers': ['technical_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Reste du framework Django (avertissements de dépréciation, etc.).
        'django': {
            'handlers': ['console', 'technical_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Logger applicatif technique : à utiliser dans le code métier pour
        # les erreurs d'API, de sauvegarde, d'import/export (logging.getLogger('app.technical')).
        'app.technical': {
            'handlers': ['technical_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Journal d'audit dédié — voir core/audit.py:log_audit().
        'app.audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}