# Generated by Django 4.2.20 on 2026-06-28 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_montant', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('nouveau_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('reste_a_payer', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Traite', 'Traite')], default='Espèces', max_length=10)),
                ('statut', models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé')], default='Payé', max_length=20)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_montant', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('nouveau_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('reste_a_payer', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Traite', 'Traite')], max_length=10)),
                ('statut', models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé')], default='Non payé', max_length=20)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_livraison_at', models.DateField()),
                ('bon_livraison_numero', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Code de bon de livraison',
                'verbose_name_plural': 'Codes de bons de livraison',
                'ordering': ['-bon_livraison_at', 'bon_livraison_numero'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('google_mape', models.TextField(blank=True, null=True, verbose_name='Lien Google Maps')),
                ('a_visiter_apres', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de jours avant la prochaine visite', null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_client'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_delegation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['gouvernorat__nom', 'nom_delegation'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_montant', models.DecimalField(decimal_places=8, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('nouveau_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('reste_a_payer', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Traite', 'Traite')], max_length=10)),
                ('statut', models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé')], default='Non payé', max_length=20)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('nom_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('type_fournisseur', models.CharField(blank=True, choices=[('Matières premières', 'Matières premières'), ('Emballages', 'Emballages'), ('Matières premières et Emballages', 'Matières premières et Emballages'), ('Équipements', 'Équipements'), ('Divers', 'Divers')], default='Matières premières et Emballages', max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('tva', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° TVA')),
                ('rib', models.CharField(blank=True, max_length=100, null=True, verbose_name='RIB')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gouvernorat',
                'verbose_name_plural': 'Gouvernorats',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_montant', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('nouveau_acompte', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('reste_a_payer', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(blank=True, choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé')], default='Payé', max_length=20, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Traite', 'Traite')], default='Espèces', max_length=10, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-vente_code__vente_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zones', to='commercial.delegation')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['delegation__nom_delegation', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='VenteDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_livraison_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vente_detaille', to='commercial.bonlivraisoncode')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commercial.vente')),
            ],
            options={
                'verbose_name': 'Détail de vente',
                'verbose_name_plural': 'Détails de ventes',
            },
        ),
        migrations.CreateModel(
            name='VenteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_at', models.DateField()),
                ('vente_numero', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventes_code', to='commercial.client')),
            ],
            options={
                'verbose_name': 'Code de vente',
                'verbose_name_plural': 'Codes de vente',
                'ordering': ['-vente_at', 'vente_numero'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='vente_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to='commercial.ventecode'),
        ),
        migrations.CreateModel(
            name='DepenseDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('valeur_unitaire', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_ligne', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commercial.depense')),
            ],
            options={
                'verbose_name': 'Détail de dépense',
                'verbose_name_plural': 'Détails de dépenses',
            },
        ),
        migrations.CreateModel(
            name='DepenseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depense_at', models.DateField()),
                ('depense_numero', models.SmallIntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='depenses_code', to='commercial.fournisseur')),
            ],
            options={
                'verbose_name': 'Code de dépense',
                'verbose_name_plural': 'Codes de dépenses',
                'ordering': ['-depense_at', 'depense_numero'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='depense_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='depenses', to='commercial.depensecode'),
        ),
        migrations.AddField(
            model_name='depense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='gouvernorat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delegations', to='commercial.gouvernorat'),
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_users', to='commercial.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation client-commercial',
                'verbose_name_plural': 'Affectations client-commerciaux',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clients', through='commercial.ClientUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='commercial.zone'),
        ),
        migrations.CreateModel(
            name='BonLivraisonDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_ligne', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='commercial.bonlivraison')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison_details', to='production.produit')),
            ],
            options={
                'verbose_name': 'Détail de bon de livraison',
                'verbose_name_plural': 'Détails de bons de livraison',
            },
        ),
        migrations.AddField(
            model_name='bonlivraisoncode',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison_code', to='commercial.client'),
        ),
        migrations.AddField(
            model_name='bonlivraisoncode',
            name='hist_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison_code', to='production.historiquestockinitial'),
        ),
        migrations.AddField(
            model_name='bonlivraisoncode',
            name='vente_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison_code', to='commercial.ventecode'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='bon_livraison_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison', to='commercial.bonlivraisoncode'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detaille_action_planifier', models.CharField(blank=True, max_length=255, null=True)),
                ('echeance_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Réaliser', 'Réaliser'), ('Annuler', 'Annuler')], default='En attente', max_length=15, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='agendas', to='commercial.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='agendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['echeance_at'],
            },
        ),
        migrations.CreateModel(
            name='AchatDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_pack', models.PositiveSmallIntegerField(default=1, help_text="Nombre d'unités par pack")),
                ('nombre_pack', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_pack', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_ligne', models.DecimalField(decimal_places=3, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)])),
                ('pack', models.BooleanField(default=False, help_text="Indique si l'achat est en mode pack")),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commercial.achat')),
                ('matiere_premiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='achat_details', to='production.matierepremiere')),
            ],
            options={
                'verbose_name': "Détail d'achat",
                'verbose_name_plural': "Détails d'achats",
            },
        ),
        migrations.CreateModel(
            name='AchatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achat_at', models.DateField()),
                ('achat_numero', models.SmallIntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='achats_code', to='commercial.fournisseur')),
            ],
            options={
                'verbose_name': "Code d'achat",
                'verbose_name_plural': "Codes d'achats",
                'ordering': ['-achat_at', 'achat_numero'],
            },
        ),
        migrations.AddField(
            model_name='achat',
            name='achat_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='achats', to='commercial.achatcode'),
        ),
        migrations.AddConstraint(
            model_name='ventecode',
            constraint=models.UniqueConstraint(fields=('vente_at', 'vente_numero'), name='unique_vente_code'),
        ),
        migrations.AddConstraint(
            model_name='depensecode',
            constraint=models.UniqueConstraint(fields=('depense_at', 'depense_numero'), name='unique_depense'),
        ),
        migrations.AddConstraint(
            model_name='bonlivraisoncode',
            constraint=models.UniqueConstraint(fields=('bon_livraison_at', 'bon_livraison_numero'), name='unique_bon_livraison_couple'),
        ),
        migrations.AddConstraint(
            model_name='achatcode',
            constraint=models.UniqueConstraint(fields=('achat_at', 'achat_numero'), name='unique_achat'),
        ),
    ]
