# Generated by Django 4.2.20 on 2026-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='users',
        ),
        migrations.AlterField(
            model_name='achatcode',
            name='achat_numero',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='depensecode',
            name='depense_numero',
            field=models.CharField(max_length=25),
        ),
    ]
