# Generated by Django 4.2.20 on 2026-07-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0002_remove_client_users_alter_achatcode_achat_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStockInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historiques_stock_initial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique stock initial',
                'verbose_name_plural': 'Historiques stock initial',
                'ordering': ['-stock_initial_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStockInitialDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcul_stock', models.PositiveSmallIntegerField(blank=True, help_text='Stock calculé système', null=True)),
                ('reel_stock', models.PositiveSmallIntegerField(blank=True, help_text='Stock réel constaté', null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('historique_stock_initial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='commercial.historiquestockinitial')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historiques_stock', to='production.produit')),
            ],
            options={
                'verbose_name': 'Détail historique stock initial',
                'verbose_name_plural': 'Détails historique stock initial',
            },
        ),
        migrations.AlterField(
            model_name='bonlivraisoncode',
            name='hist_stock_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison_code', to='commercial.historiquestockinitial'),
        ),
    ]
