# Generated by Django 4.2.20 on 2026-07-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_historiquestockinitialdetaille_historique_stock_initial_and_more'),
        ('commercial', '0003_historiquestockinitial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraisondetaille',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bons_livraison_details', to='production.produit'),
        ),
    ]
