# Generated by Django 4.2.20 on 2026-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_alter_bonlivraisondetaille_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gouvernorat',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
