# Generated by Django 4.2.20 on 2026-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_gouvernorat_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='nom_delegation',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
