# Generated by Django 4.2.20 on 2026-07-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_alter_delegation_nom_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
