# Generated by Django 4.2.20 on 2026-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_alter_zone_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='raison_sociale',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
