# Generated by Django 4.2.20 on 2026-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_fournisseur_raison_sociale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestockinitialdetaille',
            name='calcul_stock',
            field=models.SmallIntegerField(blank=True, help_text='Stock calculé système', null=True),
        ),
        migrations.AlterField(
            model_name='historiquestockinitialdetaille',
            name='reel_stock',
            field=models.SmallIntegerField(blank=True, help_text='Stock réel constaté', null=True),
        ),
    ]
