# Generated by Django 4.2.20 on 2026-08-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_alter_historiquestockinitialdetaille_calcul_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventedetaille',
            name='bon_livraison_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vente_detaille', to='commercial.bonlivraisoncode'),
        ),
    ]
