# Generated by Django 4.2.20 on 2026-08-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_alter_ventedetaille_bon_livraison_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourVisiteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_visite', to='commercial.client')),
            ],
            options={
                'verbose_name': 'Jour de visite client',
                'verbose_name_plural': 'Jours de visite client',
                'ordering': ['client', 'jour_semaine'],
            },
        ),
        migrations.AddConstraint(
            model_name='jourvisiteclient',
            constraint=models.UniqueConstraint(fields=('client', 'jour_semaine'), name='unique_jour_visite_client'),
        ),
    ]
