# Generated by Django 4.2.20 on 2026-08-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0011_jourvisiteclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence commercial',
                'verbose_name_plural': 'Absences commerciaux',
                'ordering': ['-date_debut'],
            },
        ),
    ]
