# Generated by Django 4.2.20 on 2026-08-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_absencecommercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='a_visiter_apres',
        ),
    ]
